# (PART\*) Data sharing Expectations {-}

# Elements of the DMS Plan
The NIH has provided an outline for what components of the Data Sharing and Management Plan are required.

The following are the major elements required to be included a NIH DMS plan:

1. **Data type** - describe what data (amount and type) will be generated over the course of funding and what data will or will not be shared
2. **Tools, software, and code** - describe what tools (and versions) you intend to use to manage and analyze the data (note code is not required to be shared)
3. **Standards** - describe any standards that you might need to use for your data and metadata to make them usable by others or be contributed to a repository
4. **Data preservation, access, timelines** - describe where the data will be made available and when
5. **Access, distribution, reuse considerations** - describe how you have carefully considered any reasons that might limit sharing
6. **Oversight** - describe who will manage compliance of the DMS plan

You can find more detailed requirements for each of these elements [here](https://sharing.nih.gov/data-management-and-sharing-policy/planning-and-budgeting-for-data-management-and-sharing/writing-a-data-management-and-sharing-plan#elements-to-include-in-a-data-management-and-sharing-plan). To aid in proactively planning for data management and sharing over the life of your research project, it may be helpful to consider the data types and size you plan to generate, the repositories available, and the corresponding budgetary implications before you begin your research.
## Overall Takeaways

<div class = motivations>
**Why this change?** As of January 23, 2023, the NIH is requiring all grant proposals include a Data Management and Sharing Plan to aid in the transparency and reproducibility of NIH-funded research.
</div>

<div class = question_box>
**Does this apply to me?** This will apply to most NIH grants that create data (regardless of funding level), although some grant mechanisms and some data are exempt. **It is not required to share all data**, however a justification is required. Reasons not to share that are acceptable may be ethical, technical, or legal.
</div>

<div class = data>
**Where should I share my data?** The NIH has lists of suggested repositories, to help you find appropriate repositories for your data. If there is not an appropriate repository, you can share your data at an institutional (if available) or generalist repository.
</div>

<div class = money>
**How do I budget this?** You may request funds for data management and sharing as direct costs (including personnel costs). Infrastructure costs should only be included as indirect costs.
</div>

<div class = plan>
**How do I write my plan?** Your plan should be < 2 pages (without hyperlinks) and include sections on data type; tools, software, and code; standards; data preservation, access, and timelines; access, distribution, and reuse considerations; and oversight. **You may be able to change your plan** in the just-in-time process or during regular reporting intervals. Changes require approval.
</div>

<div class = submit>
**Will my plan influence my grant score?** Although the Data Management and Sharing Plan is a mandatory part of most grant proposals, it will not be shared with reviewers and thus will not influence your score, however the budget will be visible to reviewers.
</div>

<div class = blackbox>
**Final Considerations**

This is a new policy for the NIH and they are expecting to have some growing pains. While they don't currently have specific expectations, the NIH has stated they will learn from the process as it happens along with the scientists submitting grant proposals under the new policies. In general, it's best to be mindful of what is **actually feasible** when it comes to managing and storing your data and try not overstate what you might be able to do.
</div>
