
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;
***In [memory](https://galaxyproject.org/jxtx/) of [James Taylor](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02016-0), who was instrumental in initiating this project.***

&nbsp;


|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Carrie Wright] [Candace Savonen]|
|Content Editor(s)/Reviewer(s) | [Nathan Boyd]|
|Original Authors| This course uses content from other courses authored by [Carrie Wright] [Candace Savonen], [Ava Hoffman]|
|**Technical**||
|Course Publishing Engineer(s)|[Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen]|
|Package Developers ([ottrpal]) [Candace Savonen], [John Muschelli], [Carrie Wright], [Ava Hoffman], [Kate Isaac], [Adam Coffman]|
|**Art and Design**||
|Illustrator(s)| [Carrie Wright] [Candace Savonen]|
|Figure Artist(s)| [Carrie Wright] [Candace Savonen]|
|**Funding**||
|Funder(s)| NCI UE5CA254170|
|Funding Staff| [Maleah O'Connor] [Allison (Reed) Peters]|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[Nathan Boyd]: https://datascience.cancer.gov/about/staff-directory/nathan-boyd
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Kate Isaac]: https://kweav.github.io/
[Maleah O'Connor]: https://www.linkedin.com/in/maleah-o-connor/
[Adam Coffman]: https://github.com/acoffman
[Allison (Reed) Peters]: https://www.linkedin.com/in/allisonrpeters/
<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
